#!/bin/bash
# Script to configure navigation keys with mod1

# Path to your i3 config file
CONFIG_FILE=~/.config/i3/config

# Backup the current config before making changes
cp "$CONFIG_FILE" "$CONFIG_FILE.bak"

# Replace 'mod4' with 'mod1' in the relevant sections
sed -i 's/mod4/mod1/g' "$CONFIG_FILE"

# Restore specific `mod1` bindings where needed, reversing changes only for lines that used `mod4` explicitly.
sed -i 's/bindsym mod1+ctrl+shift+p mode "\$i3exit"/bindsym mod4+ctrl+shift+p mode "\$i3exit"/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+p exec \$drun/bindsym \$mod1+p exec \$drun/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+p exec \$run/bindsym \$mod1+shift+p exec \$run/' "$CONFIG_FILE"
sed -i 's/bindsym --release \$mod4+shift+s exec \$screenshot1/bindsym --release \$mod1+shift+s exec \$screenshot1/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+shift+s exec \$screenshot2/bindsym \$mod1+ctrl+shift+s exec \$screenshot2/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+Return exec \$term/bindsym \$mod1+shift+Return exec \$term/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+c kill/bindsym \$mod1+shift+c kill/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+shift+l exec \$lock/bindsym \$mod1+ctrl+shift+l exec \$lock/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+e exec \$files/bindsym \$mod1+e exec \$files/' "$CONFIG_FILE"
sed -i 's/floating_modifier \$mod4/floating_modifier \$mod1/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+q restart/bindsym \$mod1+shift+q restart/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+r exec \$rotate/bindsym \$mod1+shift+r exec \$rotate/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+t exec \$themes/bindsym \$mod1+shift+t exec \$themes/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+\$left focus left/bindsym \$mod1+\$left focus left/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+\$down focus down/bindsym \$mod1+\$down focus down/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+\$up focus up/bindsym \$mod1+\$up focus up/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+\$right focus right/bindsym \$mod1+\$right focus right/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+\$left move left/bindsym \$mod1+shift+\$left move left/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+\$down move down/bindsym \$mod1+shift+\$down move down/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+\$up move up/bindsym \$mod1+shift+\$up move up/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+\$right move right/bindsym \$mod1+shift+\$right move right/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+Left focus left/bindsym \$mod1+Left focus left/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+Down focus down/bindsym \$mod1+Down focus down/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+Up focus up/bindsym \$mod1+Up focus up/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+Right focus right/bindsym \$mod1+Right focus right/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+Left move left/bindsym \$mod1+shift+Left move left/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+Down move down/bindsym \$mod1+shift+Down move down/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+Up move up/bindsym \$mod1+shift+Up move up/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+Right move right/bindsym \$mod1+shift+Right move right/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+1 workspace \$ws1/bindsym \$mod1+1 workspace \$ws1/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+2 workspace \$ws2/bindsym \$mod1+2 workspace \$ws2/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+3 workspace \$ws3/bindsym \$mod1+3 workspace \$ws3/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+4 workspace \$ws4/bindsym \$mod1+4 workspace \$ws4/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+5 workspace \$ws5/bindsym \$mod1+5 workspace \$ws5/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+6 workspace \$ws6/bindsym \$mod1+6 workspace \$ws6/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+7 workspace \$ws7/bindsym \$mod1+7 workspace \$ws7/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+8 workspace \$ws8/bindsym \$mod1+8 workspace \$ws8/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+9 workspace \$ws9/bindsym \$mod1+9 workspace \$ws9/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+0 workspace \$ws0/bindsym \$mod1+0 workspace \$ws0/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+1 move container to workspace number \$ws1/bindsym \$mod1+shift+1 move container to workspace number \$ws1/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+2 move container to workspace number \$ws2/bindsym \$mod1+shift+2 move container to workspace number \$ws2/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+3 move container to workspace number \$ws3/bindsym \$mod1+shift+3 move container to workspace number \$ws3/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+4 move container to workspace number \$ws4/bindsym \$mod1+shift+4 move container to workspace number \$ws4/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+5 move container to workspace number \$ws5/bindsym \$mod1+shift+5 move container to workspace number \$ws5/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+6 move container to workspace number \$ws6/bindsym \$mod1+shift+6 move container to workspace number \$ws6/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+7 move container to workspace number \$ws7/bindsym \$mod1+shift+7 move container to workspace number \$ws7/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+8 move container to workspace number \$ws8/bindsym \$mod1+shift+8 move container to workspace number \$ws8/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+9 move container to workspace number \$ws9/bindsym \$mod1+shift+9 move container to workspace number \$ws9/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+0 move container to workspace number \$ws0/bindsym \$mod1+shift+0 move container to workspace number \$ws0/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+f fullscreen/bindsym \$mod1+shift+f fullscreen/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+f floating toggle/bindsym \$mod1+f floating toggle/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+y sticky toggle/bindsym \$mod1+y sticky toggle/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+shift+x move scratchpad/bindsym \$mod1+shift+x move scratchpad/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+x scratchpad show/bindsym \$mod1+x scratchpad show/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+Right resize shrink width 100 px/bindsym \$mod1+ctrl+Right resize shrink width 100 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+Up resize grow height 50 px/bindsym \$mod1+ctrl+Up resize grow height 50 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+Down resize shrink height 50 px/bindsym \$mod1+ctrl+Down resize shrink height 50 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+Left resize grow width 100 px/bindsym \$mod1+ctrl+Left resize grow width 100 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+l resize shrink width 100 px/bindsym \$mod1+ctrl+l resize shrink width 100 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+k resize grow height 50 px/bindsym \$mod1+ctrl+k resize grow height 50 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+j resize shrink height 50 px/bindsym \$mod1+ctrl+j resize shrink height 50 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+h resize grow width 100 px/bindsym \$mod1+ctrl+h resize grow width 100 px/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+plus gaps inner current plus 5/bindsym \$mod1+ctrl+plus gaps inner current plus 5/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+minus gaps inner current minus 5/bindsym \$mod1+ctrl+minus gaps inner current minus 5/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+shift+plus gaps outer current plus 5/bindsym \$mod1+ctrl+shift+plus gaps outer current plus 5/' "$CONFIG_FILE"
sed -i 's/bindsym \$mod4+ctrl+shift+minus gaps outer current minus 5/bindsym \$mod1+ctrl+shift+minus gaps outer current minus 5/' "$CONFIG_FILE"

echo "Reverted mod4 to mod1 in $CONFIG_FILE"
