#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

xrdb -merge ~/.Xresources

# Start D-Bus session and i3
exec dbus-run-session -- i3

# Suppress the "No session for pid" warning (optional)
loginctl enable-linger $USER
